# -*- coding: utf-8 -*-
"""OCR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkkupgPdPPAMru0Y1fKrE-Q58FpuShbc
"""

!apt install tesseract-ocr -y
!pip install pytesseract pandas openpyxl Pillow

import pytesseract, pandas as pd, re
from PIL import Image, ImageEnhance, ImageFilter
from google.colab import files

print("Upload all screenshots you want to scan:")
uploaded = files.upload()

pattern = re.compile(r"(?:\+91\s*|\D)?(\d{3,5}\s*\d{5,7})")
numbers = set()

for fname in uploaded.keys():
    img = Image.open(fname).convert("L")
    img = img.filter(ImageFilter.MedianFilter())
    enhancer = ImageEnhance.Contrast(img)
    img = enhancer.enhance(2)


    text = pytesseract.image_to_string(img, config="--psm 6")


    for m in pattern.findall(text):
        clean = re.sub(r"\D", "", m)[-10:]
        if len(clean) == 10:
            numbers.add(clean)


df = pd.DataFrame(sorted(numbers), columns=["Mobile Number"])
df.to_excel("Extracted_Mobile_Numbers.xlsx", index=False)


from google.colab import files
files.download("Extracted_Mobile_Numbers.xlsx")

print(f"Done! Extracted {len(numbers)} unique 10-digit numbers.")